{
  "rootTopicKey": "566c7ba4-73e2-4ae3-a7ff-934c90ea87a0",
  "editorRootTopicKey": "566c7ba4-73e2-4ae3-a7ff-934c90ea87a0",
  "focusKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
  "extData": {
    "TOPIC_REFERENCE": {
      "reference": {}
    }
  },
  "topics": [
    {
      "key": "3b50cd3a-75f6-4851-bef0-4f8beb15a9d1",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export  CROSS_COMPILE"
        }
      ]
    },
    {
      "key": "456f871f-511d-4dfc-bfff-01eb8e614296",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "mkdir -p ${OBJTREE}/include2"
        }
      ]
    },
    {
      "key": "13e96d66-ff5d-4f6f-a44c-2411ab5915aa",
      "parentKey": "57de3f2f-124f-47f8-929d-24a4277eda22",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "> config.h"
        }
      ]
    },
    {
      "key": "a1bb2f37-2f4b-4bc0-8e14-6fe3e652aeed",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "OBJS := $(obj)cpu/$(CPU)/start.o"
        }
      ]
    },
    {
      "key": "b7058f1a-d924-4f08-aceb-b21f192b1877",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "rm -f asm"
        }
      ]
    },
    {
      "key": "41448d55-da13-4173-b697-fbe3fcf09844",
      "parentKey": "b2a33046-f43c-4d6d-8443-20c29cb7f316",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)board/*/config.tmp"
        }
      ]
    },
    {
      "key": "698c295e-3a60-4be0-9a20-f7005cde4e99",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += rtc/librtc.a"
        }
      ]
    },
    {
      "key": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [
        "ff009ab0-b0e6-4ff1-be98-1f3b16a0775c",
        "1493bdc1-d611-4fc0-ae50-0ddfbad7791c",
        "15bdc510-996a-4eaf-8905-5f6152203aa3",
        "bddeed4b-44b8-4c16-b93a-784b0a1fe3ba",
        "33df7040-6552-44a2-ab5a-c4603578ef4d",
        "a6122c81-dfb6-4800-9fa9-f91d8946c7e0",
        "b6a81ece-4605-4650-b3b0-7383dd4f28fd",
        "ef8f2aab-e465-4708-8f48-21c440ce73fb",
        "698c295e-3a60-4be0-9a20-f7005cde4e99",
        "422c18f2-9725-45fe-a44d-344f608e4c74",
        "fe891a43-0a00-4f31-8e79-057982a3c657",
        "54d2bb96-9c91-4976-8063-72df5b8ae1a3",
        "1e7e7655-7a6d-4eec-a1bd-8c33732a3594",
        "544fdf4b-33da-4d39-8ab5-bc9d9250d2ee",
        "ff21755f-e743-4765-9303-6da45602488b",
        "4b81b343-9423-41d5-b60e-f55f4503f0a5"
      ],
      "collapse": true,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS"
        }
      ]
    },
    {
      "key": "4b81b343-9423-41d5-b60e-f55f4503f0a5",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += common/libcommon.a"
        }
      ]
    },
    {
      "key": "15bdc510-996a-4eaf-8905-5f6152203aa3",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += cpu/arm920t/libarm920t.a"
        }
      ]
    },
    {
      "key": "54714f14-e62e-438f-b559-028896b9622c",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ln -s ${LNPREFIX}arch-s3c24x0 asm-arm/arch"
        }
      ]
    },
    {
      "key": "3894ef92-c9a6-4225-bc86-ddec24c3b2e7",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "rm -f asm"
        }
      ]
    },
    {
      "key": "58e83f31-f917-4e56-b738-a9e11db18c9e",
      "parentKey": "33b00e87-5b84-4db7-931d-445c965f912a",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "CC  = $(CROSS_COMPILE)gcc"
        }
      ]
    },
    {
      "key": "cdbf1a9f-ac64-422e-9722-a61653a95960",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "HOSTARCH := x86_64"
        }
      ]
    },
    {
      "key": "c2e00471-5c6b-4d4b-b53e-1dcba29221a3",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "saved-output := $(BUILD_DIR)"
        }
      ]
    },
    {
      "key": "b2a33046-f43c-4d6d-8443-20c29cb7f316",
      "parentKey": "405fb78d-8134-4656-8e6e-1bfa7ff967a2",
      "subKeys": [
        "3ed746f6-13b1-4aeb-a826-1fd8a2d8b271",
        "5164fc90-ffdc-4640-a805-5dd327445593",
        "41448d55-da13-4173-b697-fbe3fcf09844",
        "b9097740-a1bc-483d-8141-43e74f9cdaf1"
      ],
      "collapse": true,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "1. \"unconfig\"，\n删除配置时生成的文件"
        }
      ]
    },
    {
      "key": "422c18f2-9725-45fe-a44d-344f608e4c74",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += dtt/libdtt.a"
        }
      ]
    },
    {
      "key": "88118c7d-ab79-4238-90de-324f72ae9c8b",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export REMOTE_BUILD"
        }
      ]
    },
    {
      "key": "b6a81ece-4605-4650-b3b0-7383dd4f28fd",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += net/libnet.a"
        }
      ]
    },
    {
      "key": "5065384f-44b2-4add-a070-7cd74dac1b52",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LNPREFIX=\"../../include2/asm/\""
        }
      ]
    },
    {
      "key": "db7e3299-418d-44a4-a3f5-9df9c6cd54cc",
      "parentKey": "a87db9df-15bc-4c1a-91b1-95809acc7e23",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "version"
        }
      ]
    },
    {
      "key": "616a7a98-c190-493c-b99b-4f239db5b6cd",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export obj src"
        }
      ]
    },
    {
      "key": "8d1a7b52-271f-4137-a6d2-709cc479c182",
      "parentKey": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"Configuring for ${BOARD_NAME} board...\""
        }
      ]
    },
    {
      "key": "fe891a43-0a00-4f31-8e79-057982a3c657",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += drivers/libdrivers.a"
        }
      ]
    },
    {
      "key": "de76c5a0-02e0-4f99-9ae1-c62d396a1f7a",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "SUBDIRS = tools examples post post/cpu"
        }
      ]
    },
    {
      "key": "dc84044f-820a-42c9-865e-24ba62b224f2",
      "parentKey": "57de3f2f-124f-47f8-929d-24a4277eda22",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"#include <configs/smdk2410.h>\" >>config.h"
        }
      ]
    },
    {
      "key": "54d2bb96-9c91-4976-8063-72df5b8ae1a3",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += drivers/nand/libnand.a"
        }
      ]
    },
    {
      "key": "b33db6df-69cb-445f-a47b-cadf277d7cab",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [
        "a74f1ca8-a2c1-4637-99b1-1c0d94dbe4d6"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Add GCC lib"
        }
      ]
    },
    {
      "key": "fea920bd-3a16-4280-9422-76249fe69bef",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "__LIBS := $(subst $(obj),,$(LIBS))"
        }
      ]
    },
    {
      "key": "97035829-4d08-44ba-9509-eb587a928e7b",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "OBJTREE     := $(BUILD_DIR)"
        }
      ]
    },
    {
      "key": "d18c6b23-6aeb-4d51-8996-c50eb6dfdb68",
      "parentKey": "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ARCH   = arm"
        }
      ]
    },
    {
      "key": "a74f1ca8-a2c1-4637-99b1-1c0d94dbe4d6",
      "parentKey": "b33db6df-69cb-445f-a47b-cadf277d7cab",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "PLATFORM_LIBS += -L $(shell dirname `$(CC) $(CFLAGS) -print-libgcc-file-name`) -lgcc"
        }
      ]
    },
    {
      "key": "14d42a32-2f0c-44fc-8120-d7f8f86f1e7e",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export  TOPDIR SRCTREE OBJTREE"
        }
      ]
    },
    {
      "key": "64145991-3135-40fe-85a6-fd660bd1529b",
      "parentKey": "2e0e5076-9fae-465f-b2f7-112a669426ff",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"CPU    = arm920t\" >> config.mk"
        }
      ]
    },
    {
      "key": "c5ac563c-a055-4e35-87d4-32812e8b5cf3",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LNDIR       := $(OBJTREE)"
        }
      ]
    },
    {
      "key": "1b002630-64b8-48ce-a52d-c3c9acaa1cf8",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Attempt to create a output directory.\n即创建\"../build/\"目录"
        }
      ]
    },
    {
      "key": "90ccb3ef-263f-46ea-a43b-c4a2b72f2c89",
      "parentKey": "a87db9df-15bc-4c1a-91b1-95809acc7e23",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "depend"
        }
      ]
    },
    {
      "key": "bddeed4b-44b8-4c16-b93a-784b0a1fe3ba",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += cpu/arm920t/s3c24x0/libs3c24x0.a"
        }
      ]
    },
    {
      "key": "544fdf4b-33da-4d39-8ab5-bc9d9250d2ee",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += drivers/sk98lin/libsk98lin.a"
        }
      ]
    },
    {
      "key": "7c09618b-d80c-4f30-a8bb-a8d38e7622b1",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export  HOSTARCH HOSTOS"
        }
      ]
    },
    {
      "key": "57de3f2f-124f-47f8-929d-24a4277eda22",
      "parentKey": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "subKeys": [
        "13e96d66-ff5d-4f6f-a44c-2411ab5915aa",
        "ca55049e-f33f-462a-ab8e-62c2d87dda1f",
        "dc84044f-820a-42c9-865e-24ba62b224f2"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Create board specific header file"
        }
      ]
    },
    {
      "key": "3ed746f6-13b1-4aeb-a826-1fd8a2d8b271",
      "parentKey": "b2a33046-f43c-4d6d-8443-20c29cb7f316",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)include/config.h"
        }
      ]
    },
    {
      "key": "5164fc90-ffdc-4640-a805-5dd327445593",
      "parentKey": "b2a33046-f43c-4d6d-8443-20c29cb7f316",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)include/config.mk"
        }
      ]
    },
    {
      "key": "ca55049e-f33f-462a-ab8e-62c2d87dda1f",
      "parentKey": "57de3f2f-124f-47f8-929d-24a4277eda22",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"/* Automatically generated - do not edit */\" >>config.h"
        }
      ]
    },
    {
      "key": "1ff33d8a-611a-427c-9531-644629dcc193",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "VERSION_FILE = $(obj)include/version_autogenerated.h"
        }
      ]
    },
    {
      "key": "2b2fea26-27d4-4151-a8ef-ff944b2830c6",
      "parentKey": "bb89b152-a720-45cd-9aff-18371ce6ded2",
      "subKeys": [
        "4cdf4001-60bd-4745-8db3-b4b120ba02ed"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "all:        $(ALL)"
        }
      ]
    },
    {
      "key": "3292500d-6b7f-45fb-9ff1-dae712d04578",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "cd ../include"
        }
      ]
    },
    {
      "key": "8df59077-19c3-4df0-be7b-1ff2b1feb0f2",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ln -s ${LNPREFIX}proc-armv asm-arm/proc"
        }
      ]
    },
    {
      "key": "ef8f2aab-e465-4708-8f48-21c440ce73fb",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += disk/libdisk.a"
        }
      ]
    },
    {
      "key": "fb1b033c-071c-4533-8f73-8f65a73a2531",
      "parentKey": "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "CPU    = arm920t"
        }
      ]
    },
    {
      "key": "bb89b152-a720-45cd-9aff-18371ce6ded2",
      "parentKey": "566c7ba4-73e2-4ae3-a7ff-934c90ea87a0",
      "subKeys": [
        "3a4325ef-d583-4844-aba8-629e117b27b0",
        "2b2fea26-27d4-4151-a8ef-ff944b2830c6"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "make O=../build/ all"
        }
      ]
    },
    {
      "key": "bf0d1fb5-fd68-488a-9ebf-33daccb3ae89",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ln -s ${SRCTREE}/include/asm-arm asm"
        }
      ]
    },
    {
      "key": "a6122c81-dfb6-4800-9fa9-f91d8946c7e0",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += fs/cramfs/libcramfs.a fs/fat/libfat.a fs/fdos/libfdos.a fs/jffs2/libjffs2.a fs/reiserfs/libreiserfs.a fs/ext2/libext2fs.a"
        }
      ]
    },
    {
      "key": "2daec20d-5821-4ca1-a405-fb0dc36c90f5",
      "parentKey": "4cdf4001-60bd-4745-8db3-b4b120ba02ed",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)u-boot.bin"
        }
      ]
    },
    {
      "key": "fef46441-cb6a-4285-81d4-6ea0adb4ff6d",
      "parentKey": "debaea30-07e2-40b7-85e1-134dfce1e778",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(OBJCOPY) ${OBJCFLAGS} -O srec $< $@"
        }
      ]
    },
    {
      "key": "2e0e5076-9fae-465f-b2f7-112a669426ff",
      "parentKey": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "subKeys": [
        "2fc2a3f1-dff1-41fc-9fc7-8d7f2a7b5c5b",
        "64145991-3135-40fe-85a6-fd660bd1529b",
        "54aa2eda-6114-40de-8e5d-1541b267dd6d",
        "9be25326-634a-4b41-b2d2-17605e5bdbec"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Create include file for Make"
        }
      ]
    },
    {
      "key": "a3aebebd-0e3b-443c-8a78-6dec2d61390f",
      "parentKey": "a87db9df-15bc-4c1a-91b1-95809acc7e23",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "..."
        }
      ]
    },
    {
      "key": "54aa2eda-6114-40de-8e5d-1541b267dd6d",
      "parentKey": "2e0e5076-9fae-465f-b2f7-112a669426ff",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"BOARD  = smdk2410 \" >> config.mk"
        }
      ]
    },
    {
      "key": "566c7ba4-73e2-4ae3-a7ff-934c90ea87a0",
      "parentKey": null,
      "subKeys": [
        "405fb78d-8134-4656-8e6e-1bfa7ff967a2",
        "bb89b152-a720-45cd-9aff-18371ce6ded2"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Makefile"
        }
      ]
    },
    {
      "key": "30a37b64-828c-4282-baf3-39cb67185947",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "SRCTREE     := $(CURDIR)"
        }
      ]
    },
    {
      "key": "80c23239-473a-4b1d-bfc7-bdbdfbecd1bf",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "obj := $(OBJTREE)/"
        }
      ]
    },
    {
      "key": "e51baa62-0c47-475d-a62b-f4191d341ecd",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "__OBJS := $(subst $(obj),,$(OBJS))"
        }
      ]
    },
    {
      "key": "9be25326-634a-4b41-b2d2-17605e5bdbec",
      "parentKey": "2e0e5076-9fae-465f-b2f7-112a669426ff",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"SOC    = s3c24x0\" >> config.mk"
        }
      ]
    },
    {
      "key": "33b00e87-5b84-4db7-931d-445c965f912a",
      "parentKey": "3421e88c-7fd1-4811-91eb-3065543a5c6e",
      "subKeys": [
        "e9b47338-9b4a-432b-9885-9ce99de10bb2",
        "58e83f31-f917-4e56-b738-a9e11db18c9e"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "include $(TOPDIR)/config.mk"
        }
      ]
    },
    {
      "key": "ff21755f-e743-4765-9303-6da45602488b",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += post/libpost.a post/cpu/libcpu.a"
        }
      ]
    },
    {
      "key": "e47dcdca-b8a0-4541-8b7a-0ed7113bbd94",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "HOSTOS := linux"
        }
      ]
    },
    {
      "key": "6927f2f8-4c3c-46a3-a63a-149adcd346ab",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ln -s asm-arm asm"
        }
      ]
    },
    {
      "key": "868edf06-f79b-4dd6-9901-49cdb8b82f1f",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "BUILD_DIR := ../build/"
        }
      ]
    },
    {
      "key": "c1cd07fe-762e-4683-a331-989244c4f89c",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "REMOTE_BUILD    := 1"
        }
      ]
    },
    {
      "key": "7e1f8cfb-a98a-48ae-bb3b-cf992ed5d595",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Verify if it was successful.\n验证是否创建文件夹成功"
        }
      ]
    },
    {
      "key": "10045d71-8cb4-46ed-947b-9dc34ef67e79",
      "parentKey": "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "BOARD  = smdk2410"
        }
      ]
    },
    {
      "key": "a333145f-0332-45f3-9758-5f2bae2fd881",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "rm -f asm-arm/proc"
        }
      ]
    },
    {
      "key": "3421e88c-7fd1-4811-91eb-3065543a5c6e",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [
        "33b00e87-5b84-4db7-931d-445c965f912a"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "load other configuration"
        }
      ]
    },
    {
      "key": "3e2ae117-f9fc-4fb0-9ecc-58ee9e266dfe",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "rm -f asm-arm/arch"
        }
      ]
    },
    {
      "key": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "parentKey": "bb89b152-a720-45cd-9aff-18371ce6ded2",
      "subKeys": [
        "032ba006-7874-4d59-ba06-e1b5a4b59730",
        "1ff33d8a-611a-427c-9531-644629dcc193",
        "cdbf1a9f-ac64-422e-9722-a61653a95960",
        "e47dcdca-b8a0-4541-8b7a-0ed7113bbd94",
        "7c09618b-d80c-4f30-a8bb-a8d38e7622b1",
        "868edf06-f79b-4dd6-9901-49cdb8b82f1f",
        "c2e00471-5c6b-4d4b-b53e-1dcba29221a3",
        "1b002630-64b8-48ce-a52d-c3c9acaa1cf8",
        "7e1f8cfb-a98a-48ae-bb3b-cf992ed5d595",
        "97035829-4d08-44ba-9509-eb587a928e7b",
        "30a37b64-828c-4282-baf3-39cb67185947",
        "8e919cd2-0b2e-431c-8c5c-9e0c1c9f6bba",
        "c5ac563c-a055-4e35-87d4-32812e8b5cf3",
        "14d42a32-2f0c-44fc-8120-d7f8f86f1e7e",
        "c1cd07fe-762e-4683-a331-989244c4f89c",
        "88118c7d-ab79-4238-90de-324f72ae9c8b",
        "80c23239-473a-4b1d-bfc7-bdbdfbecd1bf",
        "bd82ff98-6859-46dc-8233-51adda38a519",
        "616a7a98-c190-493c-b99b-4f239db5b6cd",
        "41901b18-0221-49a6-bb1c-9ec3291c4f42",
        "d2a2e2a2-266a-40d7-b921-5f3538254a4b",
        "3b50cd3a-75f6-4851-bef0-4f8beb15a9d1",
        "3421e88c-7fd1-4811-91eb-3065543a5c6e",
        "a1bb2f37-2f4b-4bc0-8e14-6fe3e652aeed",
        "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
        "1d6e50ab-d2b1-4853-a6f8-b3623f31b6d1",
        "b33db6df-69cb-445f-a47b-cadf277d7cab",
        "de76c5a0-02e0-4f99-9ae1-c62d396a1f7a",
        "e51baa62-0c47-475d-a62b-f4191d341ecd",
        "fea920bd-3a16-4280-9422-76249fe69bef"
      ],
      "collapse": true,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "变量"
        }
      ]
    },
    {
      "key": "1493bdc1-d611-4fc0-ae50-0ddfbad7791c",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += board/smdk2410/libsmdk2410.a"
        }
      ]
    },
    {
      "key": "ff009ab0-b0e6-4ff1-be98-1f3b16a0775c",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS  = lib_generic/libgeneric.a"
        }
      ]
    },
    {
      "key": "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
      "parentKey": "41901b18-0221-49a6-bb1c-9ec3291c4f42",
      "subKeys": [
        "d18c6b23-6aeb-4d51-8996-c50eb6dfdb68",
        "fb1b033c-071c-4533-8f73-8f65a73a2531",
        "10045d71-8cb4-46ed-947b-9dc34ef67e79",
        "9373346d-3bca-4d31-982e-053373ba4ada"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "include $(OBJTREE)/include/config.mk"
        }
      ]
    },
    {
      "key": "ec865305-01bb-4081-a2dc-370e4c51f887",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "rm -rf asm-arm"
        }
      ]
    },
    {
      "key": "41901b18-0221-49a6-bb1c-9ec3291c4f42",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [
        "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
        "58be0f32-a7d3-4d97-b591-e5d7a6d20097"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "load ARCH, BOARD, and CPU configuration"
        }
      ]
    },
    {
      "key": "4cdf4001-60bd-4745-8db3-b4b120ba02ed",
      "parentKey": "2b2fea26-27d4-4151-a8ef-ff944b2830c6",
      "subKeys": [
        "debaea30-07e2-40b7-85e1-134dfce1e778",
        "2daec20d-5821-4ca1-a405-fb0dc36c90f5",
        "7565d2a8-d4fd-4ff8-8ec9-2694d6f28f70",
        "151c71fd-e0f8-4360-b4a6-414f01c1d68a"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "ALL = $(obj)u-boot.srec $(obj)u-boot.bin $(obj)System.map $(U_BOOT_NAND)"
        }
      ]
    },
    {
      "key": "8e919cd2-0b2e-431c-8c5c-9e0c1c9f6bba",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "TOPDIR      := $(SRCTREE)"
        }
      ]
    },
    {
      "key": "032ba006-7874-4d59-ba06-e1b5a4b59730",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "U_BOOT_VERSION = 1.1.6"
        }
      ]
    },
    {
      "key": "7565d2a8-d4fd-4ff8-8ec9-2694d6f28f70",
      "parentKey": "4cdf4001-60bd-4745-8db3-b4b120ba02ed",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)System.map"
        }
      ]
    },
    {
      "key": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "parentKey": "405fb78d-8134-4656-8e6e-1bfa7ff967a2",
      "subKeys": [
        "bb95069d-e3ad-4fcb-9097-0a656cd70c35",
        "8d1a7b52-271f-4137-a6d2-709cc479c182",
        "7b77fbf4-24f9-43e6-b767-502d32c72256",
        "2e0e5076-9fae-465f-b2f7-112a669426ff",
        "57de3f2f-124f-47f8-929d-24a4277eda22"
      ],
      "collapse": true,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "2. \"./mkconfig smdk2410 arm arm920t smdk2410 NULL s3c24x0\"，\n执行mkconfig"
        }
      ]
    },
    {
      "key": "bd82ff98-6859-46dc-8233-51adda38a519",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "src := $(SRCTREE)/"
        }
      ]
    },
    {
      "key": "1e7e7655-7a6d-4eec-a1bd-8c33732a3594",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += drivers/nand_legacy/libnand_legacy.a"
        }
      ]
    },
    {
      "key": "c59cbf33-80e6-4f5a-9d29-dbbada332274",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "mkdir asm-arm"
        }
      ]
    },
    {
      "key": "debaea30-07e2-40b7-85e1-134dfce1e778",
      "parentKey": "4cdf4001-60bd-4745-8db3-b4b120ba02ed",
      "subKeys": [
        "a87db9df-15bc-4c1a-91b1-95809acc7e23",
        "fef46441-cb6a-4285-81d4-6ea0adb4ff6d"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)u-boot.srec"
        }
      ]
    },
    {
      "key": "405fb78d-8134-4656-8e6e-1bfa7ff967a2",
      "parentKey": "566c7ba4-73e2-4ae3-a7ff-934c90ea87a0",
      "subKeys": [
        "b2a33046-f43c-4d6d-8443-20c29cb7f316",
        "5656f7ae-f30f-4406-8050-29471b6ba480"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "make O=../build/ smdk2410_config"
        }
      ]
    },
    {
      "key": "1d6e50ab-d2b1-4853-a6f8-b3623f31b6d1",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS := $(addprefix $(obj),$(LIBS))"
        }
      ]
    },
    {
      "key": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "parentKey": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "subKeys": [
        "89f9d116-da7f-44d8-86b4-e809a7103c66",
        "456f871f-511d-4dfc-bfff-01eb8e614296",
        "b58541dd-8ad6-4056-be78-5fdccc5e567f",
        "b7058f1a-d924-4f08-aceb-b21f192b1877",
        "bf0d1fb5-fd68-488a-9ebf-33daccb3ae89",
        "5065384f-44b2-4add-a070-7cd74dac1b52",
        "3292500d-6b7f-45fb-9ff1-dae712d04578",
        "ec865305-01bb-4081-a2dc-370e4c51f887",
        "3894ef92-c9a6-4225-bc86-ddec24c3b2e7",
        "c59cbf33-80e6-4f5a-9d29-dbbada332274",
        "6927f2f8-4c3c-46a3-a63a-149adcd346ab",
        "3e2ae117-f9fc-4fb0-9ecc-58ee9e266dfe",
        "54714f14-e62e-438f-b559-028896b9622c",
        "a333145f-0332-45f3-9758-5f2bae2fd881",
        "8df59077-19c3-4df0-be7b-1ff2b1feb0f2"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "Create link to architecture specific headers"
        }
      ]
    },
    {
      "key": "b58541dd-8ad6-4056-be78-5fdccc5e567f",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "cd ${OBJTREE}/include2"
        }
      ]
    },
    {
      "key": "a87db9df-15bc-4c1a-91b1-95809acc7e23",
      "parentKey": "debaea30-07e2-40b7-85e1-134dfce1e778",
      "subKeys": [
        "90ccb3ef-263f-46ea-a43b-c4a2b72f2c89",
        "db7e3299-418d-44a4-a3f5-9df9c6cd54cc",
        "a3aebebd-0e3b-443c-8a78-6dec2d61390f"
      ],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)u-boot"
        }
      ]
    },
    {
      "key": "e9b47338-9b4a-432b-9885-9ce99de10bb2",
      "parentKey": "33b00e87-5b84-4db7-931d-445c965f912a",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "BOARDDIR = $(BOARD)"
        }
      ]
    },
    {
      "key": "2fc2a3f1-dff1-41fc-9fc7-8d7f2a7b5c5b",
      "parentKey": "2e0e5076-9fae-465f-b2f7-112a669426ff",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "echo \"ARCH   = arm\" >  config.mk"
        }
      ]
    },
    {
      "key": "151c71fd-e0f8-4360-b4a6-414f01c1d68a",
      "parentKey": "4cdf4001-60bd-4745-8db3-b4b120ba02ed",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(U_BOOT_NAND)"
        }
      ]
    },
    {
      "key": "d2a2e2a2-266a-40d7-b921-5f3538254a4b",
      "parentKey": "3a4325ef-d583-4844-aba8-629e117b27b0",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "CROSS_COMPILE = arm-linux-"
        }
      ]
    },
    {
      "key": "58be0f32-a7d3-4d97-b591-e5d7a6d20097",
      "parentKey": "41901b18-0221-49a6-bb1c-9ec3291c4f42",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "export  ARCH CPU BOARD VENDOR SOC"
        }
      ]
    },
    {
      "key": "bb95069d-e3ad-4fcb-9097-0a656cd70c35",
      "parentKey": "5656f7ae-f30f-4406-8050-29471b6ba480",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "BOARD_NAME = smdk2410"
        }
      ]
    },
    {
      "key": "9373346d-3bca-4d31-982e-053373ba4ada",
      "parentKey": "3c093073-2bfc-4323-8da9-49ca4bbd77ae",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "SOC    = s3c24x0"
        }
      ]
    },
    {
      "key": "33df7040-6552-44a2-ab5a-c4603578ef4d",
      "parentKey": "525b4a72-a6f6-4484-b2ad-0f515c6360a6",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "LIBS += lib_arm/libarm.a"
        }
      ]
    },
    {
      "key": "b9097740-a1bc-483d-8141-43e74f9cdaf1",
      "parentKey": "b2a33046-f43c-4d6d-8443-20c29cb7f316",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "$(obj)board/*/*/config.tmp"
        }
      ]
    },
    {
      "key": "89f9d116-da7f-44d8-86b4-e809a7103c66",
      "parentKey": "7b77fbf4-24f9-43e6-b767-502d32c72256",
      "subKeys": [],
      "collapse": false,
      "style": null,
      "blocks": [
        {
          "type": "CONTENT",
          "data": "mkdir -p ${OBJTREE}/include"
        }
      ]
    }
  ],
  "config": {
    "readOnly": false,
    "allowUndo": true,
    "layoutDir": 0,
    "theme": {
      "name": "theme2",
      "randomColor": false,
      "background": "#f8f8f8",
      "highlightColor": "#50C9CE",
      "marginH": 45,
      "marginV": 10,
      "contentStyle": {
        "lineHeight": "1.5"
      },
      "linkStyle": {
        "lineRadius": 5
      },
      "rootTopic": {
        "contentStyle": {
          "background": "#50C18A",
          "color": "#fff",
          "fontSize": "34px",
          "borderRadius": "5px",
          "padding": "16px 18px 16px 18px"
        },
        "subLinkStyle": {
          "lineType": "curve",
          "lineWidth": "2px",
          "lineColor": "#43a9ff"
        }
      },
      "primaryTopic": {
        "contentStyle": {
          "background": "#ffffff",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderColor": "rgb(221, 170, 68)",
          "borderRadius": "5px",
          "color": "rgb(103,103,103)",
          "fontSize": "14px",
          "padding": "6px 10px 5px 10px"
        },
        "subLinkStyle": {
          "lineType": "round",
          "lineRadius": 5,
          "lineWidth": "2px",
          "lineColor": "#43a9ff"
        }
      },
      "normalTopic": {
        "contentStyle": {
          "background": "#fff",
          "borderRadius": "5px",
          "color": "rgb(103,103,103)",
          "fontSize": "13px",
          "padding": "3px 9px 4px",
          "boxShadow": "1px 1px 1px #ccc"
        },
        "subLinkStyle": {
          "lineType": "round",
          "lineRadius": 5,
          "lineWidth": "1px",
          "lineColor": "#43a9ff"
        }
      }
    }
  },
  "formatVersion": "0.0"
}